### GET hello
GET http://localhost:8888/hello

### GET gw
GET http://localhost:8888/gw

### post user
POST http://localhost:8888/gw/io.github.alfaio.afrpc.demo.api.UserService
Content-Type: application/json

{
  "service":"io.github.alfaio.afrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

### GET gw
GET http://localhost:8888/gw/afrpc/

### POST DirectPlugin
POST http://localhost:8888/gw/direct/io.github.alfaio.afrpc.demo.api.UserService?backend=http://localhost:8081/afrpc
Content-Type: application/json

{
  "service":"io.github.alfaio.afrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

### POST AfrpcPlugin
POST http://localhost:8888/gw/afrpc/io.github.alfaio.afrpc.demo.api.UserService?backend=1
Content-Type: application/json

{
  "service":"io.github.alfaio.afrpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}